FROM ubuntu:jammy

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y \
    openssh-server \
    ca-certificates \
    sudo \
    curl \
    git \
    zsh

CMD ["bash", "-c", "cat $DOTFILES_VOLUME_DIR/install.sh | bash -s -- $INSTALL_SCRIPT_PARAMS"]
